name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build and publish to PyPI
        run: |
          pip install build twine
          python -m build
          python -m twine upload dist/* --username __token__ --password ${{ secrets.PYPI_TOKEN }}
